# Generated by Django 5.2.7 on 2026-04-07 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('position_type', models.CharField(choices=[('F', 'Fielder'), ('P', 'Pitcher')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PitcherStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g', models.IntegerField(default=0)),
                ('p', models.IntegerField(default=0)),
                ('pcl', models.FloatField(default=0.0)),
                ('j', models.IntegerField(default=0)),
                ('a', models.IntegerField(default=0)),
                ('jc', models.IntegerField(default=0)),
                ('bl', models.IntegerField(default=0)),
                ('sv', models.IntegerField(default=0)),
                ('il', models.FloatField(default=0.0)),
                ('h', models.IntegerField(default=0)),
                ('cl', models.IntegerField(default=0)),
                ('so', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='FielderStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j', models.IntegerField(default=0)),
                ('tb', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('h2', models.IntegerField(default=0)),
                ('h3', models.IntegerField(default=0)),
                ('h4', models.IntegerField(default=0)),
                ('cis', models.IntegerField(default=0)),
                ('bb', models.IntegerField(default=0)),
                ('bbi', models.IntegerField(default=0)),
                ('so', models.IntegerField(default=0)),
                ('br', models.IntegerField(default=0)),
                ('ar', models.IntegerField(default=0)),
                ('pro', models.FloatField(default=0.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_app.player')),
            ],
        ),
    ]
